### ISSUE TITLE
Metrics Tweaks Revisited

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse-metrics#17]
- [ ] Add months to the X axis of the charts that are now displaying 36 months. See issue #22 and pull request #23.
- [ ] Show Github contributors (at a minimum). Note there is a github API for this: https://developer.github.com/v3/repos/statistics/. Consider including an option to not display this (for those installations running the tool). See issue #16 and pull request #21.
- [ ] Apply text change Gary wants for "Metrics are aggregated from" from 9d46627 . See pull request #24.

**Comment by pdurbin** [comment]
At design standup I talked through all the issues and pull requests above with @TaniaSchlatter @scolapasta and @mheppler and we ultimately decided to send them all to QA as-is. We have dreams for metrics but this issue was estimated as a "small" and we're trying to keep to that.

I talked to @kcondon afterwards and offered to put all three pull requests into one. He said he's fine with testing and merging them separately. He has already merged one which led to merge conflicts in another, which I have resolved.

**Comment by pdurbin** [comment]
I released https://github.com/IQSS/dataverse-metrics/releases/tag/v0.2.5 and @donsizemore deployed it to https://dataverse.org/metrics with month_filter_enabled set to true and github_repos with the main "dataverse" repo. I think it's looking good! The months are back, we see contributors, and the wording has been updated. Here's a screenshot:

![Metrics_The_Dataverse_Project_-_Dataverse org_-_2019-06-04_13 52 40](https://user-images.githubusercontent.com/21006/58902032-580bd200-86d0-11e9-8e84-7bc99a513d90.png)
